[input]
cd_offset = [0, 2, 50, 3]
cd_origin = "top-center"
cd_title = "Change directory:"
create_offset = [0, 2, 50, 3]
create_origin = "top-center"
create_title = ["Create:", "Create (dir):"]
delete_offset = [0, 2, 50, 3]
delete_origin = "top-center"
delete_title = "Delete {n} selected file{s} permanently? (y/N)"
filter_offset = [0, 2, 50, 3]
filter_origin = "top-center"
filter_title = "Filter:"
find_offset = [0, 2, 50, 3]
find_origin = "top-center"
find_title = ["Find next:", "Find previous:"]
overwrite_offset = [0, 2, 50, 3]
overwrite_origin = "top-center"
overwrite_title = "Overwrite an existing file? (y/N)"
quit_offset = [0, 2, 50, 3]
quit_origin = "top-center"
quit_title = "{n} task{s} running, sure to quit? (y/N)"
rename_offset = [0, 1, 50, 3]
rename_origin = "hovered"
rename_title = "Rename:"
search_offset = [0, 2, 50, 3]
search_origin = "top-center"
search_title = "Search via {n}:"
shell_offset = [0, 2, 50, 3]
shell_origin = "top-center"
shell_title = ["Shell:", "Shell (block):"]
trash_offset = [0, 2, 50, 3]
trash_origin = "top-center"
trash_title = "move {n} selected file{s} to trash? (y/n)"

[log]
enabled = false

[mgr]
linemode = "permissions"
mouse_events = ["click", "scroll"]
ratio = [1, 3, 3]
show_hidden = true
show_symlink = false
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[[open.rules]]
name = "*/"
use = ["edit", "editVS", "open", "reveal", "look"]

[[open.rules]]
mime = "text/*"
use = ["edit", "editVS", "open", "reveal"]

[[open.rules]]
mime = "application/json"
use = ["edit", "editVS", "reveal"]

[[open.rules]]
mime = "*/javascript"
use = ["edit", "editVS", "reveal"]

[[open.rules]]
mime = "image/*"
use = ["open", "reveal", "look"]

[[open.rules]]
mime = "video/*"
use = ["play", "reveal", "look"]

[[open.rules]]
mime = "audio/*"
use = ["play", "reveal", "look"]

[[open.rules]]
mime = "inode/x-empty"
use = ["edit", "reveal"]

[[open.rules]]
mime = "application/zip"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/gzip"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-tar"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-bzip"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-bzip2"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-7z-compressed"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-rar"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/xz"
use = ["extract", "reveal"]

[[open.rules]]
mime = "*"
use = ["edit", "open", "reveal", "look"]

[[opener.edit]]
block = true
desc = "Edit via $EDITOR"
for = "unix"
run = "$EDITOR \"$@\""

[[opener.edit]]
block = true
desc = "Edit via $EDITOR"
for = "windows"
orphan = true
run = "%EDITOR% \"%*\""

[[opener.editVS]]
block = true
desc = "Edit via VSCode"
for = "unix"
run = "code \"$@\""

[[opener.editVS]]
desc = "Edit via VSCode"
for = "windows"
orphan = true
run = "code \"%*\""

[[opener.extract]]
desc = "Extract Here"
for = "unix"
run = "ouch d \"$1\""

[[opener.extract]]
desc = "Extract Here"
for = "windows"
run = "ouch d \"%1\""

[[opener.look]]
desc = "QuickLook"
for = "macos"
run = "qlmanage -p \"$@\""

[[opener.open]]
desc = "Default Open"
for = "linux"
run = "xdg-open \"$@\""

[[opener.open]]
desc = "Default Open"
for = "macos"
run = "open \"$@\""

[[opener.open]]
desc = "Default Open"
for = "windows"
orphan = true
run = "start \"\" \"%1\""

[[opener.play]]
desc = "Play via mpv"
for = "unix"
orphan = true
run = "mpv --force-window \"$@\""

[[opener.play]]
desc = "Play via mpv"
for = "windows"
orphan = true
run = "mpv --force-window \"%1\""

[[opener.reveal]]
desc = "Finder reveal"
for = "macos"
run = "open -R \"$1\""

[[opener.reveal]]
desc = "Explorer reveal"
for = "windows"
orphan = true
run = "explorer /select, \"%1\""

[[plugin.append_previewers]]
name = "*"
run = "file"

[[plugin.preloaders]]
mime = "image/vnd.djvu"
run = "noop"

[[plugin.preloaders]]
mime = "image/*"
run = "image"

[[plugin.preloaders]]
mime = "video/*"
run = "video"

[[plugin.preloaders]]
mime = "application/pdf"
run = "pdf"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
mime = "application/*zip"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-tar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-bzip2"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-7z-compressed"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-rar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-xz"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
mime = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
mime = "*.ipynb"
run = "rich-preview"

[[plugin.previewers]]
name = "*/"
run = "folder"
sync = true

[[plugin.previewers]]
mime = "text/*"
run = "code"

[[plugin.previewers]]
mime = "*/xml"
run = "code"

[[plugin.previewers]]
mime = "*/javascript"
run = "code"

[[plugin.previewers]]
mime = "*/x-wine-extension-ini"
run = "code"

[[plugin.previewers]]
mime = "application/json"
run = "json"

[[plugin.previewers]]
mime = "image/vnd.djvu"
run = "noop"

[[plugin.previewers]]
mime = "image/*"
run = "image"

[[plugin.previewers]]
mime = "video/*"
run = "video"

[[plugin.previewers]]
mime = "application/pdf"
run = "pdf"

[[plugin.previewers]]
mime = "application/zip"
run = "archive"

[[plugin.previewers]]
mime = "application/gzip"
run = "archive"

[[plugin.previewers]]
mime = "application/x-tar"
run = "archive"

[[plugin.previewers]]
mime = "application/x-bzip"
run = "archive"

[[plugin.previewers]]
mime = "application/x-bzip2"
run = "archive"

[[plugin.previewers]]
mime = "application/x-7z-compressed"
run = "archive"

[[plugin.previewers]]
mime = "application/x-rar"
run = "archive"

[[plugin.previewers]]
mime = "application/xz"
run = "archive"

[[plugin.previewers]]
mime = "*"
run = "hexyl"

[preview]
cache_dir = ""
image_delay = 100
image_filter = "nearest"
image_quality = 50
max_height = 2000
max_width = 2000
sixel_fraction = 15
tab_size = 2
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1
wrap = "no"

[select]
open_offset = [0, 1, 50, 7]
open_origin = "hovered"
open_title = "Open with:"

[tasks]
bizarre_retry = 5
image_alloc = 536870912
image_bound = [0, 0]
macro_workers = 25
micro_workers = 10
suppress_preload = false