dialect = "uk"
enter_accept = false
exit_mode = "return-original"
filter_mode = "global"
filter_mode_shell_up_key_binding = "directory"
inline_height = 10
invert = false
keymap_mode = "emacs"
show_help = false
show_preview = false
style = "full"
workspaces = true

[keymap_cursor]
emacs = "steady-bar"
vim_insert = "steady-bar"
vim_normal = "steady-block"
