
# See https://github.com/rszyma/kanata-tray for help with configuration.

configurations = [
    "
]

executables = [

]

[layer_icons]


[general]
include_executables_from_system_path = true
include_configs_from_default_locations = true
launch_on_start = true
