'$schema' = 'https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json'

[general]
allow_concurrent_presets = false

[defaults]
kanata_executable = "C:\\Users\\div\\Projects\\kanata\\target\\release\\kanata.exe" # if empty or omitted, system $PATH will be searched.
kanata_config = "C:\\Users\\div\\.config\\kanata\\a.kbd" # if empty or not omitted, kanata default config locations will be used.
tcp_port = 5829 # if not specified, defaults to 5829

[presets.'main cfg']
kanata_executable = "C:\\Users\\div\\Projects\\kanata\\target\\release\\kanata.exe" # if empty or omitted, system $PATH will be searched.
kanata_config = "C:\\Users\\div\\.config\\kanata\\a.kbd" # if empty or not omitted, kanata default config locations will be used.
autorun = true


